/****** Object:  Table [dbo].[Amigo]    Script Date: 07/04/2018 16:49:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Amigo](
	[AmigoId] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](100) NULL,
	[Latitude] [Float] NULL,
	[Longitude] [Float] NULL,
 CONSTRAINT [PK_Amigo_AmigoId] PRIMARY KEY CLUSTERED 
(
	[AmigoId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [DADOS]
) ON [DADOS]

GO

SET ANSI_PADDING OFF
GO